import type { Product, ProductWithPricesAndMedia } from '../products.types';

export const mockProduct: Product = {
  id: 1,
  organizationId: 1,
  sku: 'SKU-001',
  externalSku: 'EXT-001',
  externalName: 'External Product',
  name: 'Test Product',
  description: 'Test Description',
  productType: 'simple',
  status: 'active',
  unitOfMeasure: 'unit',
  brand: 'Test Brand',
  model: 'Model-001',
  taxClassId: 1,
  weight: '1.5',
  height: '10',
  width: '20',
  length: '30',
  metadata: { size: 'M', color: 'blue' },
  prices: [],
  media: [],
  inventory: [],
};

export const mockProductWithPricesAndMedia: ProductWithPricesAndMedia = {
  ...mockProduct,
  prices: [
    {
      id: 1,
      price_list_id: 1,
      currency: 'CLP',
      amount: '10000',
      tax_included: false,
      valid_from: '2024-01-01T00:00:00Z',
      valid_to: null,
      created_at: '2024-01-01T00:00:00Z',
      price_list_name: 'Default',
      price_list_is_default: true,
    },
  ],
  media: [
    {
      id: 1,
      type: 'image',
      url: 'https://example.com/image.jpg',
      position: 1,
      alt_text: 'Test Image',
      title: 'Test Title',
      description: null,
      file_size: 1024,
      mime_type: 'image/jpeg',
      is_primary: true,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  inventory: [
    {
      id: 1,
      product_id: 1,
      location_id: 1,
      on_hand: '100',
      reserved: '10',
      updated_at: '2024-01-01T00:00:00Z',
      location_code: 'WH-001',
      location_name: 'Warehouse 1',
      location_type: 'warehouse',
      available: 90,
    },
  ],
};

export const mockDbProduct = {
  id: 1,
  organizationId: 1,
  sku: 'SKU-001',
  externalSku: null,
  externalName: null,
  name: 'Product 1',
  description: null,
  productType: 'simple',
  status: 'active',
  unitOfMeasure: null,
  brand: null,
  model: null,
  taxClassId: null,
  weight: null,
  height: null,
  width: null,
  length: null,
  metadata: null,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockDbProducts = [
  mockDbProduct,
  {
    id: 2,
    organizationId: 1,
    sku: 'SKU-002',
    externalSku: null,
    externalName: null,
    name: 'Product 2',
    description: null,
    productType: 'simple',
    status: 'active',
    unitOfMeasure: null,
    brand: null,
    model: null,
    taxClassId: null,
    weight: null,
    height: null,
    width: null,
    length: null,
    metadata: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockRelatedProduct = {
  id: 2,
  organizationId: 1,
  sku: 'SKU-002',
  externalSku: null,
  externalName: null,
  name: 'Related Product',
  description: null,
  productType: 'simple',
  status: 'active',
  unitOfMeasure: null,
  brand: null,
  model: null,
  taxClassId: null,
  weight: null,
  height: null,
  width: null,
  length: null,
  metadata: null,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockRelation = {
  id: 1,
  productId: 1,
  relatedProductId: 2,
  organizationId: 1,
  relationType: 'related' as const,
  quantity: '1',
  position: 0,
  isActive: true,
  createdAt: new Date(),
  updatedAt: new Date(),
  relatedProduct: mockRelatedProduct,
};

export const mockProductMedia = {
  id: 1,
  productId: 1,
  type: 'image',
  url: 'https://example.com/image.jpg',
  position: 1,
  altText: null,
  title: null,
  description: null,
  fileSize: null,
  mimeType: null,
  isPrimary: false,
  organizationId: 1,
  createdAt: new Date(),
  updatedAt: new Date(),
};

